dependencies:
- name: activiti-cloud-full-example
  repository: https://activiti.github.io/activiti-cloud-helm-charts/
  version: 0.0.210
- name: example-runtime-bundle
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.1.76
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
